export const oberlinData = [
    'Help',
    'Try catch is producing an error',
    'test!',
    'Implementing the scanner is producing an error',
    '??? so many',
    'User inputs',
    'looping through arrays',
    'vs code de;ting our code',
    'Commenting in java',
    'll',
    'Returning an array',
    'trying to figure out the layout of the lab lol name is baks',
    'scanners',
    'userplayer deciderank method',
    'non-static variable rank cannot be referenced from a static context',
    'confusion about the lab instructions',
    'Several including break notaiton',
    'Need help with terminal syntax',
    'deciderank method',
    'Forgive me lord for I have syntaxed',
    'Card',
    'dealing with exceptions',
    'Reviewing code',
    'looking at the cards and seeing what they are',
    'Can I consult your wisdom?',
    'deciderank method',
    "can't figure out how to return chosen rank, also when I put in a char, it does weird things.",
    'Just want to chat...',
    'I have many questions regarding syntax and instruction comprehension',
    'Need some ayuda',
    'Still issues with my count',
    'I need some help debugging',
    'I do not understand.',
    'I am having trouble getting my code to run',
    'about requestCard',
    'Error: Canot evoke Card.getRank() because this.hand is null',
    'the middlle loop',
    'lab 2',
    'Need to know how to tell python to change colors of a shape that I create using "picture" module.',
    "Have no idea with the triple loop and the saving expression value didn't match the right one",
    'error messages w/ shape',
    'spiral.py',
    "I'm confused about the loops require for spiral, fancy spiral and savings.",
    'just confused about the code',
    "I don't even know where to start",
    'requestcards',
    'patternN',
    "I'm just really confused in general about pattern N. I made a code for " +
        "the first astericks but I can't seem to figure out the rest.",
    'compiling but not running',
    'requestCards method and checkBooks method'
];