import * as express from 'express';
import * as session from 'express-session';
import * as bodyparser from 'body-parser';
import * as path from 'path';
import postgraphql from 'postgraphql';
import * as passport from 'passport';
import * as sslRedirect from 'heroku-ssl-redirect';

import { graphqlExpress, graphiqlExpress } from 'graphql-server-express'
import { makeExecutableSchema, addMockFunctionsToSchema } from 'graphql-tools';
import { graphql } from 'graphql';
import { readFileSync, readFile } from 'fs'

const app = express();
app.use(sslRedirect());

// Initialize session middleware
var sessionOptions = {
    secret: (process.env.OH_SESSION_SECRET || "<veWHM#Q9a<k8^"),
    cookie: {
        secure: false
    }
}

if (app.get('env') === 'production') {
    app.set('trust proxy', 1) // trust first proxy
    sessionOptions.cookie.secure = true // serve secure cookies
}

app.use(session(sessionOptions))

// Initialize Passport and Strategy
app.use(passport.initialize());
app.use(passport.session());
var GoogleStrategy = require('passport-google-oauth20').Strategy;

passport.use(new GoogleStrategy(
    {
        clientID: "694487664328-79nbgbrnm3n3sa3nfsdfm5jigkr69svp.apps.googleusercontent.com",
        clientSecret: process.env.OH_GOOGLE_SECRET,
        callbackURL: "/__auth/callback",
        userProfileURL: "https://www.googleapis.com/oauth2/v3/userinfo",
    },
    function (accessToken, refreshToken, profile, cb) {
        console.log(profile.id)

        return (cb(null, profile))
        // user_id (should be autogenerated), netId, GoogleId, firstName, lastName, createdAt, lastActivityAt

        // SELECT * FROM users where "googleId" = ''

        // INSERT INTO users
        // ("netId", "googleId", "firstName", "lastName", "createdAt", "lastActivityAt") VALUES
        // ('rms427', 'slamajama', 'Ryan', 'Slama', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)

        // User.findOrCreate({ googleId: profile.id }, function (err, user) {
        //     return cb(err, user);
        // });
    }
))

passport.serializeUser(function (user, done) {
    // @ts-ignore
    done(null, user.id)
})

passport.deserializeUser(function (user, done) {
    done(null, user)
})

app.get('/__auth',
    passport.authenticate('google', {
        scope: ['email'],
        // @ts-ignore: Hosted domain is used by the Google strategy, but not allowed in passport's types
        hostedDomain: "cornell.edu"
    })
)
app.get('/__auth/callback',
    passport.authenticate('google', { failureRedirect: '/login' }),
    function (req, res) {
        console.log("Callback:")
        console.log(req.user)
        res.redirect('/');
    }
)

app.get('/__sess',
    function (req, res) {
        console.log("####################")
        console.log("Session Test:")
        console.log(req.user)
        if (req.user == undefined) {
            res.redirect('/login');
        }
        res.send(req.user)
    }
)

const schemaString = readFileSync('schema.gql').toString();

// Make a GraphQL schema with no resolvers
const schema = makeExecutableSchema({ typeDefs: schemaString });

app.use(postgraphql(process.env.DATABASE_URL || 'postgres://localhost:5432', {
    graphiql: true,
    graphqlRoute: '/__gql/graphql',
    graphiqlRoute: '/__gql/graphiql',
    jwtSecret: (process.env.OH_JWT_SECRET || "<veWHM#Q9a<k8^"),
    // pgSettings: req => ({
    //     role: 'app_visitor', ...(req.user && req.user.id ? { "jwt.claims.user_id": String(req.user.id) } : null),
    // })
}));

app.use(express.static('../client/build'));
app.listen(process.env.PORT || 3001, () => {
    console.log("Now listening on port " + (process.env.PORT || 3001));
});
