type Post {
  id: ID!
  text: String!
  author: User!
}

type User {
  id: ID!
  name: String!
  posts: [Post]
}

type Query {
  viewer: User
  user(id: Int!): User
}

type Mutation {
  changeName(id: ID!, newName: String!): User
}

type Subscription {
  nameChanged(id: ID): [User]
}
