type Course {
  id: ID!
  name: String!
  semester: String!
  students: [Student!]
  # All the tas for this course.
  tas: [Student!]
  # All the sessions for this course.
  sessions: [Session!]
  # All the tags for this course
  tags: [Tag!]
}

type Student {
  netid: ID!
  name: String!
  courses: [Course!]
  following: [Question!]
}

type Session {
  id: ID!
  start: Int!
  end: Int!
  location: String!
  course: Course!
  tas: [Student!]
  questions: [Question!]
}

type Question {
  id: ID!
  text: String!
  time_entered: String!
  session: Session!
  student: Student!
  tags: [Tag!]
  followers: [Student!]
}

type Tag {
  id: ID!
  value: String!
  course: Course!
  questions: [Question!]
}

type Query {
  student(netid: ID!): Student
  course(name: String!): Course
}
