type User {
  id: ID!
  name: String!
}

type Query {
  viewer: User
  user(id: Int!): User
}

type Mutation {
  changeName(id: ID!, newName: String!): User
}

type Subscription {
  nameChanged(id: ID): [User]
}
