name: CI
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Pin to Yarn 1.18
        run: yarn policies set-version 1.18
      - name: Install and Build
        run: yarn install
      - name: Lint client
        run: cd client && yarn tslint --project tsconfig.json -c tslint.json 'src/**/*.ts' 'src/**/*.tsx'
