name: CI
on: pull_request

jobs:
  warn-big-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cornell-dti/big-diff-warning@master
        env:
          BOT_TOKEN: '${{ secrets.BOT_TOKEN }}'
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install and Build
        run: yarn install
      - name: Lint client
        run: cd client && yarn install && yarn lint
