name: CI
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Install and Build
        run: yarn install
      - name: Lint client
        run: cd client && yarn tslint --project .
      - name: Lint server
        run: cd server && yarn tslint --project .
