name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install
        run: yarn install
      - name: Install for client
        run: cd client && yarn install
      - name: Lint client
        run: cd client && yarn lint
