name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "^20.19.0"
      - name: Install
        run: |
          yarn install
          cd functions
          yarn install
      - name: Lint client
        run: yarn lint
      - name: Type Check
        run: yarn tsc
      - name: Run Tests
        run: yarn test
